modules:
  - data_ingestion
  - classification
  - db_update

classification:
  codes:
    - code: "snid"
      config_file: "/path/to/snid/config.yml"
    - code: "ngsf"
      config_file: "/path/to/other_code/config.yml"